FROM node:12.7.0-alpine

RUN npm install --global @vue/cli

WORKDIR /app

COPY ./app/package.json /app
COPY ./app/package-lock.json /app

RUN echo $PWD

RUN npm install 

COPY ./app /app

CMD ["npm","run", "serve"]